export { default as 'Baby Blue' } from './Baby Blue.css?inline'
export { default as 'Burgundy Pink' } from './Burgundy Pink.css?inline'
export { default as 'Chiffon' } from './Chiffon.css?inline'
export { default as 'Copper' } from './Copper.css?inline'
export { default as 'Creamy Pink' } from './Creamy Pink.css?inline'
export { default as 'Deep Sea' } from './Deep Sea.css?inline'
export { default as 'Flamingo' } from './Flamingo.css?inline'
export { default as 'Flower' } from './Flower.css?inline'
export { default as 'Grey and Beige' } from './Grey and Beige.css?inline'
export { default as 'Midnight' } from './Midnight.css?inline'
export { default as 'Old Parchment' } from './Old Parchment.css?inline'
export { default as 'Purple Space' } from './Purple Space.css?inline'
export { default as 'Raspberry' } from './Raspberry.css?inline'
export { default as 'Retro Gold' } from './Retro Gold.css?inline'
export { default as 'Saphire Peach' } from './Saphire Peach.css?inline'
