# ascii engine settings
# All fields are optional. Missing fields fall back to engine defaults.

[game]
title = "Laser Chess"
disable_context_menu = true
initial_theme = "Desert Sunset"
engine_themes = []
# "Chiffon", "Copper", "Flamingo", "Grey and Beige", "Midnight", "Old Parchment", "Raspberry", "Retro Gold", "Saphire Peach"

[world]
chunk_view_distance = 3

[camera]
half_life = 300  # ms to close half the distance to target
initial_position = [15, 15]

[bindings]
pause       = ["Escape", "ShiftLeft"]
confirm     = ["Enter", "NumpadEnter", "Space"]
cancel      = ["Escape", "ShiftLeft"]
up          = ["KeyW", "ArrowUp", "Numpad7", "Numpad8", "Numpad9"]
down        = ["KeyS", "ArrowDown", "Numpad1", "Numpad2", "Numpad3"]
left        = ["KeyA", "ArrowLeft", "Numpad1", "Numpad4", "Numpad7"]
right       = ["KeyD", "ArrowRight", "Numpad3", "Numpad6", "Numpad9"]
flip_mirror = ["ShiftLeft"]